###################################################################
#### References                                                ####
###################################################################
## https://www.kaggle.com/holar9/house-price-prediction-stacking-top-15-lb
###################################################################
#### Feature engineering                                       ####
###################################################################
neighborhood.bin <- c('MeadowV' = 0, 'IDOTRR' = 1, 'Sawyer' = 1, 'BrDale' = 1, 'OldTown'= 1,
                      'Edwards' = 1, 'BrkSide' = 1, 'Blueste' = 1, 'SWISU' = 2, 'NAmes' = 2,
                      'NPkVill' = 2, 'Mitchel' = 2,'SawyerW' = 2, 'Gilbert' = 2, 'NWAmes'=2,
                      'Blmngtn' = 2, 'CollgCr' = 2, 'ClearCr' = 3,'Crawfor' =3, 'Veenker'=3,
                      'Somerst' = 3, 'Timber' = 3, 'StoneBr' = 4, 'NoRidge'= 4,'NridgHt' =4)
overallCond.bin <- c('1' = 1, '2'= 1, '3' = 1, '4' = 2,'5' = 2, '6' = 2, '7' = 3, '8' = 3,
             '      9' = 3)
overallCond.bin <- c('1' = 1, '2'= 1, '3' = 1, '4' = 2,'5' = 2, '6' = 2, '7' = 3, '8' = 3,
                     '      9' = 3)
houseStyle.bin <- c("1Story" = "1Story", 
                    "1.5Fin" = "1.5Story", 
                    "1.5Unf" = "1.5Story",
                    "2.5Unf" = "2.5Story",
                    "2.5Fin" = "2.5Story",
                    "2Story" = "2Story",
                    "SFoyer" = "SFoyer",
                    "SLvl" = "SLvl") 
full.dt[, ':=' (
               BinNeighborhood = as.factor(neighborhood.bin[Neighborhood]), 
               BinOverallCond = as.integer(overallCond.bin[OverallCond]), 
               BinHouseStyle = as.factor(houseStyle.bin[HouseStyle]),
               hasShed = ifelse(MiscFeature == "Shed",1,0),
               hasOpenPorch = ifelse(OpenPorchSF > 0,1,0),
               hasEnclosedPorch = ifelse(EnclosedPorch > 0,1,0),
               hasThreeSsnPorch = ifelse(ThreeSsnPorch > 0,1,0),
               hasScreenPorch = ifelse(ScreenPorch > 0,1,0),
               hasSecondFloor = ifelse(SecondFlrSF > 0,1,0),
               hasHasMasVnr = ifelse(MasVnrArea > 0,1,0),
               hasHasWoodDeck = ifelse(WoodDeckSF > 0,1,0),
               hasBadHeating = ifelse(HeatingQC %in% c("Fa","Po"),1,0),
               hasPavedDrive = ifelse(PavedDrive == "Y",1,0),
               hasElectricalSBrkr = ifelse(Electrical == "SBrkr",1,0),
               hasRegLotShape = ifelse(LotShape == "Reg",1,0),
               hasLvlLandContour = ifelse(LandContour == "Lvl",1,0),
               hasGtlLandSlope = ifelse(LandSlope == "Gtl",1,0),
               hasDetchdGarage = ifelse(GarageType == 'Detchd',1,0),
               hasUnfinishedLevel= ifelse(HouseStyle %in% c("1.5Unf","2.5Unf"),1,0),
               hasRoofMatlWoodCly = ifelse(RoofMatl %in% c("WdShake","WdShngl","ClyTile"),1,0),
               hasRoofTar = ifelse(RoofMatl == "Tar&Grv",1,0), 
               hasRoofCompShg = ifelse(RoofMatl == "CompShg",1,0), 
               isNewerDwelling = ifelse(MSSubClass %in% c(20,60,120),1,0),
               isRemodeled = ifelse(YearRemodAdd == YearBuilt, 1, 0),
               isRemodeledRecent = ifelse(YearRemodAdd == YrSold, 1, 0),
               isNew = ifelse(YearBuilt == YrSold, 1, 0),
               isNormalSale = ifelse(SaleCondition %in% c("Normal","Partial"), 1, 0),
               isConditionNearRail    = ifelse(Condition1 %in% c("RRAe","RRAn","RRNe","RRNn") | Condition2 %in% c("RRAe","RRAn","RRNe","RRNn"),1,0),
               isConditionNearArtery  = ifelse(Condition1 == "Artery" | Condition2 == "Artery",1,0),
               isConditionNearFeedr  = ifelse(Condition1 == "Feedr" | Condition2 == "Feedr",1,0),
               isConditionNearPosFeature  = ifelse(Condition1 %in% c("PosA"," PosN") | Condition2 %in% c("PosA"," PosN"),1,0),
               ageInYears = YrSold - YearBuilt,
               soldHighSeason = ifelse(MoSold %in% c(5,6,7),1,0),
               yearsSinceRemodeled = ifelse(YearRemodAdd == YearBuilt, YrSold - YearRemodAdd, 0),
               sfFloors = FirstFlrSF + SecondFlrSF,
               sfAboveGradeAndBasement = TotalBsmtSF + GrLivArea,
               sfTotal          = (TotalBsmtSF + FirstFlrSF + SecondFlrSF),
               scoreOverall = as.integer(OverallQual) * as.integer(OverallCond),
               scoreBasement = as.integer(BsmtQual) * as.integer(BsmtCond),
               scoreExterior = as.integer(ExterQual) * as.integer(ExterCond),
               countBathrooms = BsmtFullBath +  BsmtHalfBath + FullBath + HalfBath,
                BsmtCond = NULL,
                BsmtFullBath = NULL,
                BsmtHalfBath = NULL,
                BsmtQual = NULL,
                Condition1 = NULL, 
                Condition2 = NULL,  
                Electrical = NULL,
                EnclosedPorch = NULL,
                ExterCond = NULL,
                ExterQual = NULL,
                FirstFlrSF = NULL,
                FullBath = NULL,
                GarageType = NULL,
                HalfBath = NULL,
                HeatingQC = NULL,
                HouseStyle = NULL,
                LandContour = NULL,
                LandSlope = NULL,
                MasVnrArea = NULL,
                MiscFeature = NULL,
                MoSold = NULL,
                MSSubClass = NULL,
                Neighborhood = NULL,
                OpenPorchSF = NULL, 
                OverallCond = NULL,
                OverallQual = NULL,
                PavedDrive = NULL,
                RoofMatl = NULL, 
                SaleCondition = NULL,
                ScreenPorch = NULL,
                SecondFlrSF = NULL,
                ThreeSsnPorch = NULL,
                TotalBsmtSF = NULL,
                Utilities = NULL,
                WoodDeckSF = NULL,
                YearBuilt = NULL,
                YearRemodAdd = NULL,
                YrSold = NULL
)]
